In [1]:
import pandas as pd

In [14]:
df = pd.read_csv("ventas_bogota_limpiar (1).csv",
                  sep=";", 
                  encoding="utf-8")

In [15]:
df

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor r,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audefenes,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,TeCladO,Acxexorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audefenes,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audefenes,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,196,7/03/2024,TeCladO,Periféricos,1093703.74,5,BOGOTA,NaN,si
201,197,19/03/2024,TeCladO,Periféricos,2851075.64,4,NaN,Transferencia,si
202,198,10/03/2024,Laptop,Electrónica,2401288.14,8,NaN,Transferencia,NO
203,199,3/02/2024,Audefenes,Accesorios,581720.03,6,bogotá,tarjeta,NaN
204,200,24/05/2024,Monitor r,Acxexorios,3189581.24,2,Cali,Tarjeta,Sí

'''Ejercicio 26: Filtrado con método .isin()
* Contexto: Queremos aislar registros que pertenezcan exclusivamente a un conjunto específico de ciudades clave.
* Instrucción: Utiliza el método .isin(["Bogotá", "Cali"]) sobre la columna "ciudad" para filtrar el DataFrame 
y conservar únicamente las transacciones de estas dos ciudades. Muestra el número total de registros coincidentes.'''

In [ ]:
ciudades_clave = df[df["ciudad"].isin(["Bogotá", "Cali"])]

#ciudades_clave.groupby("ciudad")["precio"].sum()

#print("Total de registros:", len(ciudades_clave))

In [19]:
ciudades_clave.groupby("ciudad")["precio"].sum()

ciudad
Bogotá    58157023.17
Cali      59727204.18
Name: precio, dtype: float64

In [20]:
print("Total de registros:", len(ciudades_clave))

Total de registros: 65

Ejercicio 27: Combinación de Datos - Cruce Relacional (pd.merge)
* Contexto: Integraremos una tabla externa con tasas de bonificación comercial basadas en el método de pago utilizado.
* Instrucción: Crea un DataFrame secundario con las columnas “metodo_pago” (ej. “Tarjeta”, “Efectivo”, “Transferencia”) y 
“bonificacion” (ej. [0.05, 0.02, 0.03]). Realiza un cruce relacional tipo left join (pd.merge) utilizando la columna en común. 
Muestra las primeras 4 filas del resultado.''

In [21]:
import pandas as pd

In [32]:
# Crear DataFrame con las tasas de bonificación
df_bonificacion = pd.DataFrame({
    "metodo_pago": ["Tarjeta", "Efectivo", "Transferencia"],
    "bonificacion": [0.05, 0.02, 0.03]
})

df_bonificacion

     metodo_pago  bonificacion
0        Tarjeta          0.05
1       Efectivo          0.02
2  Transferencia          0.03

In [36]:
df2 = pd.read_csv("ventas_bogota_limpiar (1).csv",
                  sep=";", 
                  encoding="utf-8")

In [37]:
df2

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor r,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audefenes,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,TeCladO,Acxexorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audefenes,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audefenes,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,196,7/03/2024,TeCladO,Periféricos,1093703.74,5,BOGOTA,NaN,si
201,197,19/03/2024,TeCladO,Periféricos,2851075.64,4,NaN,Transferencia,si
202,198,10/03/2024,Laptop,Electrónica,2401288.14,8,NaN,Transferencia,NO
203,199,3/02/2024,Audefenes,Accesorios,581720.03,6,bogotá,tarjeta,NaN
204,200,24/05/2024,Monitor r,Acxexorios,3189581.24,2,Cali,Tarjeta,Sí

In [39]:
# Unión usando pd.merge con dirección left
df_unido = pd.merge(
    df,
    df_bonificacion,
    on="metodo_pago",
    how="left"
)

df_unido.head(4)

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho,bonificacion
0,1,13/02/2024,Monitor r,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si,0.05
1,2,29/02/2024,Audefenes,Accesorios,2786223.89,2,Barranquilla,NaN,si,NaN
2,3,5/04/2024,TeCladO,Acxexorios,958850.40,3,Cali,NaN,No,NaN
3,4,12/05/2024,Audefenes,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN,0.02

Ejercicio 18: Limpieza de Nulos - Relleno de Texto

Contexto: Las celdas vacías en columnas categóricas como el método de pago afectan los reportes de segmentación.

Instrucción: Rellena los valores nulos (NaN) de la columna "metodo_pago" utilizando el texto "No registrado" mediante el método .fillna(). Muestra un conteo de nulos actualizado para esa columna.

In [40]:
df = pd.read_csv("ventas_bogota_limpiar (1).csv",
                  sep=";", 
                  encoding="utf-8")

In [46]:
# Rellenar los valores nulos con "No registrado"

df["metodo_pago"] = df["metodo_pago"].fillna("No registrado")

print(f"Cantidad de nulos en metodo_pago después de limpiar: {df['metodo_pago'].isna().sum()}")

Cantidad de nulos en metodo_pago después de limpiar: 0

Ejercicio 21: Ordenamiento de Datos - Ascendente

Texto:

Contexto: Se requiere listar las transacciones ordenadas de menor a mayor precio unitario para análisis de presupuestos accesibles.

Instrucción: Ordena el DataFrame en función de la columna "precio" de forma ascendente (ascending=True) utilizando .sort_values(). Muestra las primeras 3 filas del resultado.

In [48]:
df = pd.read_csv("ventas_bogota_limpiar (1).csv",
                  sep=";", 
                  encoding="utf-8")

In [49]:
df_ordenado = df.sort_values("precio", ascending=True)

df_ordenado.head(3)

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
105,101,1/05/2024,Monitor r,Electrónica,52769.22,8,Cali,tarjeta,No
154,150,2/04/2024,Monitor r,Periféricos,54567.45,7,BOGOTA,Efectivo,NaN
168,164,5/03/2024,Laptop,Periféricos,57358.34,2,BOGOTA,NaN,Sí

Ejercicio 9: Manejo de Errores (try-except)
Contexto: Al procesar datos externos o realizar operaciones matemáticas, pueden ocurrir errores imprevistos como divisiones por cero o accesos a índices inexistentes.
Instrucción: Escribe un bloque try-except que intente dividir el primer valor de la columna "precio" entre cero (df.loc[0, "precio"] / 0). Captura la excepción específica de tipo ZeroDivisionError e imprime un mensaje amigable indicando que la operación no es válida.

In [50]:
try:
    resultado = df.loc[0, "precio"] / 0
    print(resultado)

except ZeroDivisionError:
    print("La operación no es válida: no se puede dividir entre cero.")

inf

/var/folders/2t/9j68zq6976b_kr0nwv849h680000gn/T/ipykernel_66629/4128062133.py:2: RuntimeWarning: divide by zero encountered in scalar divide
  resultado = df.loc[0, "precio"] / 0

In [52]:
df

,id_venta,fecha,producto,categoria,precio,cantidad,ciudad,metodo_pago,cliente_satisfecho
0,1,13/02/2024,Monitor r,Accesorios,1140503.31,6,Barranquilla,Tarjeta,si
1,2,29/02/2024,Audefenes,Accesorios,2786223.89,2,Barranquilla,NaN,si
2,3,5/04/2024,TeCladO,Acxexorios,958850.40,3,Cali,NaN,No
3,4,12/05/2024,Audefenes,Periféricos,1544815.40,5,Barranquilla,Efectivo,NaN
4,5,13/05/2024,Audefenes,Periféricos,NaN,9,bogotá,tarjeta,Sí
...,...,...,...,...,...,...,...,...,...
200,196,7/03/2024,TeCladO,Periféricos,1093703.74,5,BOGOTA,NaN,si
201,197,19/03/2024,TeCladO,Periféricos,2851075.64,4,NaN,Transferencia,si
202,198,10/03/2024,Laptop,Electrónica,2401288.14,8,NaN,Transferencia,NO
203,199,3/02/2024,Audefenes,Accesorios,581720.03,6,bogotá,tarjeta,NaN
204,200,24/05/2024,Monitor r,Acxexorios,3189581.24,2,Cali,Tarjeta,Sí

In [53]:
df.loc[0, "precio"]

np.float64(1140503.31)

Ejercicio 1: Variables y Tipos de Datos Básicos

Contexto: Antes de procesar el DataFrame completo, necesitamos almacenar configuraciones iniciales y constantes para nuestro script de análisis.

Instrucción: Define una variable llamada nombre_empresa con el valor "Bogotá Retail S.A.", una variable tasa_impuesto con el valor 0.19 (float) y una variable activo con el valor True (booleano). Imprime los tres valores junto con su tipo de datos utilizando la función type().

In [1]:

# 1. Crear variable de texto
nombre_empresa = "Bogotá Retail S.A."

# 2. Crear variable decimal
tasa_impuesto = 0.19

# 3. Crear variable booleana
activo = True

# 4. Mostrar los valores
print(nombre_empresa)
print(tasa_impuesto)
print(activo)

# 5. Mostrar el tipo de cada variable
print(type(nombre_empresa))
print(type(tasa_impuesto))
print(type(activo))

Bogotá Retail S.A.
0.19
True
<class 'str'>
<class 'float'>
<class 'bool'>

Ejercicio 2: Operadores Aritméticos y Asignación

Contexto: Se requiere calcular de forma manual el valor bruto de una transacción unitaria antes de integrarlo al DataFrame general.

Instrucción: Define dos variables numéricas: precio_unitario = 1500000 y cantidad_unidades = 3. Utiliza operadores aritméticos para calcular el subtotal (precio por cantidad), agrégale un recargo fijo de 25000 por envío mediante el operador de asignación acumulativa (+=), e imprime el resultado final.

In [2]:

# 1. Crear el precio unitario
precio_unitario = 1500000

# 2. Crear la cantidad de unidades
cantidad_unidades = 3

# 3. Calcular el subtotal
subtotal = precio_unitario * cantidad_unidades

# 4. Agregar el recargo de envío
subtotal += 25000

# 5. Mostrar el resultado final
print(subtotal)

4525000

Ejercicio 3: Carga del DataFrame con Pandas

Contexto: El primer paso operativo en cualquier proyecto de datos es importar las fuentes externas y garantizar una lectura estructurada limpia.

Instrucción: Importa pandas as pd. Carga el archivo ventas_bogota_limpiar.csv usando el separador ; y la codificación "latin-1". Guarda el resultado en la variable df y muestra sus dimensiones mediante la propiedad .shape.

In [3]:
# 1. Importar pandas
import pandas as pd

# 2. Cargar el archivo CSV
df = pd.read_csv(
    "ventas_bogota_limpiar.csv",
    sep=";",
    encoding="latin-1"
)

# 3. Mostrar las dimensiones del DataFrame
print(df.shape)

(205, 9)


Ejercicio 4: Condicionales Simples (if)

Contexto: Queremos evaluar dinámicamente el precio del primer producto del dataset para clasificarlo comercialmente.

Instrucción: Extrae el valor del precio de la primera fila (df.loc[0, 'precio']). Utiliza una estructura condicional if-else para evaluar si el precio es mayor a 1,000,000. Si es verdadero, imprime "Producto de gama alta", de lo contrario, imprime "Producto estándar".

In [4]:
# 1. Extraer el precio de la primera fila
precio = df.loc[0, "precio"]

# 2. Evaluar el precio
if precio > 1000000:
    print("Producto de gama alta")
else:
    print("Producto estándar")

Producto de gama alta

Ejercicio 5: Condicionales Múltiples (if-elif-else)

Contexto: Necesitamos categorizar el volumen de unidades vendidas en la primera transacción del dataset bajo criterios de escala operativa.

Instrucción: Extrae la cantidad de la primera fila (df.loc[0, 'cantidad']). Diseña una estructura condicional múltiple: si la cantidad es mayor o igual a 8, imprime "Venta mayorista"; si está entre 4 y 7, imprime "Venta mediana"; de lo contrario, imprime "Venta minorista".

In [5]:
# 1. Extraer la cantidad de la primera fila
cantidad = df.loc[0, "cantidad"]

# 2. Clasificar la venta
if cantidad >= 8:
    print("Venta mayorista")

elif cantidad >= 4:
    print("Venta mediana")

else:
    print("Venta minorista")

Venta mediana

Ejercicio 6: Bucle for sobre Series de Pandas

Contexto: Queremos iterar de forma explícita sobre los primeros elementos de una columna para aplicar una revisión visual rápida.

Instrucción: Utiliza un bucle for para recorrer los primeros 5 elementos de la columna "producto" (df['producto'].head()) e imprime cada nombre de producto precedido por el texto "Artículo registrado: ".

In [6]:
# Recorrer los primeros 5 productos
for producto in df["producto"].head():
    
    # Mostrar cada producto
    print("Artículo registrado:", producto)

Artículo registrado: Monitor
Artículo registrado: AudÃ­fonos
Artículo registrado: Teclado
Artículo registrado: AudÃ­fonos
Artículo registrado: AudÃ­fonos

Ejercicio 7: Bucle while y Control de Índices

Contexto: Simularemos el procesamiento iterativo de las primeras filas de nuestro DataFrame utilizando un control de flujo por índice numérico con while.

Instrucción: Inicializa una variable de control i = 0. Utiliza un bucle while para iterar mientras i < 3, imprimiendo el ID de venta y la ciudad correspondiente utilizando df.loc[i, 'id_venta'] y df.loc[i, 'ciudad']. Incrementa el contador en cada iteración.

In [10]:
print(df.columns)

Index(['ï»¿id_venta', 'fecha', 'producto', 'categoria', 'precio', 'cantidad',
       'ciudad', 'metodo_pago', 'cliente_satisfecho'],
      dtype='str')

In [11]:
df.columns = df.columns.str.replace("ï»¿", "", regex=False)

In [12]:
# 1. Crear el contador
i = 0

# 2. Repetir mientras i sea menor que 3
while i < 3:

    # 3. Obtener el ID de venta
    id_venta = df.loc[i, "id_venta"]

    # 4. Obtener la ciudad
    ciudad = df.loc[i, "ciudad"]

    # 5. Mostrar los datos
    print("ID:", id_venta, "| Ciudad:", ciudad)

    # 6. Aumentar el contador
    i += 1

ID: 1 | Ciudad: Barranquilla
ID: 2 | Ciudad: Barranquilla
ID: 3 | Ciudad: Cali

Ejercicio 8: Creación de Funciones (def)

Contexto: Automatizaremos el cálculo del valor total de una venta para reutilizarlo en diferentes procesos de análisis.

Instrucción: Define una función llamada calcular_total(precio, cantidad) que reciba ambos valores como parámetros y retorne el producto de ellos. Pruébala enviando un precio de 250000 y una cantidad de 4, e imprime el resultado.

In [13]:
# 1. Crear la función
def calcular_total(precio, cantidad):

    # 2. Multiplicar precio por cantidad
    return precio * cantidad


# 3. Probar la función
resultado = calcular_total(250000, 4)


# 4. Mostrar el resultado
print(resultado)

1000000

Ejercicio 10: Inspección Básica del DataFrame

Contexto: Conocer la estructura de tipos de datos y la presencia de valores nulos es fundamental antes de realizar operaciones de limpieza.

Instrucción: Utiliza el método .info() sobre el DataFrame df para revisar los tipos de datos asignados a cada columna y el conteo de registros no nulos.

In [14]:
# Inspección básica del DataFrame

# Mostrar información general del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_venta            205 non-null    int64
 1   fecha               205 non-null    str
 2   producto            205 non-null    str
 3   categoria           205 non-null    str
 4   precio              190 non-null    float64
 5   cantidad            205 non-null    int64
 6   ciudad              196 non-null    str
 7   metodo_pago         163 non-null    str
 8   cliente_satisfecho  163 non-null    str
dtypes: float64(1), int64(2), str(6)
memory usage: 14.5 KB

Ejercicio 11: Estadísticas Descriptivas Básicas

Contexto: Necesitamos obtener un panorama general del comportamiento numérico de las columnas cuantitativas.

Instrucción: Ejecuta el método .describe() sobre el DataFrame para visualizar métricas estadísticas clave como media, valores mínimos y máximos de las columnas numéricas.

In [15]:
df.describe()

         id_venta        precio    cantidad
count  205.000000  1.900000e+02  205.000000
mean    98.365854  1.778548e+06    4.800000
std     58.745361  1.062617e+06    2.616689
min      1.000000  5.276922e+04    1.000000
25%     47.000000  9.050350e+05    2.000000
50%     98.000000  1.806900e+06    5.000000
75%    149.000000  2.662794e+06    7.000000
max    200.000000  3.475482e+06    9.000000

Ejercicio 12: Selección de Columnas Específicas

Contexto: Para un análisis financiero enfocado, requerimos aislar un subconjunto de columnas relevantes.

Instrucción: Selecciona las columnas "id_venta", "fecha", "producto" y "precio" del DataFrame principal, guárdalas en un nuevo DataFrame llamado df_financiero y muestra sus primeras 3 filas.

In [16]:

# 1. Seleccionar las columnas necesarias
df_financiero = df[[
    "id_venta",
    "fecha",
    "producto",
    "precio"
]]

# 2. Mostrar las primeras 3 filas
print(df_financiero.head(3))

   id_venta       fecha    producto      precio
0         1  2024-02-13     Monitor  1140503.31
1         2  2024-02-29  AudÃ­fonos  2786223.89
2         3  2024-04-05     Teclado   958850.40

Ejercicio 13: Filtrado de Datos por Condición Simple

Contexto: El equipo comercial solicita un reporte exclusivo de todas las transacciones realizadas en la ciudad de Cali.

Instrucción: Filtra el DataFrame df para conservar únicamente las filas donde la columna "ciudad" sea igual a "Cali". Guarda el resultado en df_cali y muestra su tamaño mediante .shape.

In [17]:

# 1. Filtrar las filas donde la ciudad sea Cali
df_cali = df[df["ciudad"] == "Cali"]

# 2. Mostrar el tamaño del resultado
print(df_cali.shape)

(35, 9)

Ejercicio 14: Filtrado de Datos con Múltiples Condiciones (&)

Contexto: Se requiere identificar transacciones de alto valor volumétrico en una categoría específica de productos.

Instrucción: Aplica un filtro combinado sobre df para obtener aquellas filas donde la "cantidad" sea mayor o igual a 5 y la "categoria" sea exactamente "Accesorios". Muestra las primeras 3 filas del resultado.

In [18]:
# 1. Filtrar:
# cantidad mayor o igual a 5
# Y categoría igual a Accesorios

df_accesorios = df[
    (df["cantidad"] >= 5) &
    (df["categoria"] == "Accesorios")
]

# 2. Mostrar las primeras 3 filas
print(df_accesorios.head(3))

    id_venta       fecha producto   categoria      precio  cantidad  \
0          1  2024-02-13  Monitor  Accesorios  1140503.31         6
8          9  2024-03-19  Teclado  Accesorios         NaN         5
26        27  2024-05-22  Teclado  Accesorios   419513.15         7

          ciudad metodo_pago cliente_satisfecho
0   Barranquilla     Tarjeta                 si
8        bogotÃ¡         NaN                 si
26  Barranquilla    Efectivo                NaN

Ejercicio 15: Creación de Columna Calculada (Venta Total)

Contexto: El dataset contiene precio unitario y cantidad, pero necesitamos la métrica monetaria total por transacción.

Instrucción: Crea una nueva columna en el DataFrame llamada "venta_total" multiplicando los valores de "precio" por "cantidad". Imprime las primeras 4 filas de las columnas "id_venta", "precio", "cantidad" y "venta_total".

In [19]:
# Creación de columna calculada: venta_total

# 1. Crear la columna venta_total
df["venta_total"] = df["precio"] * df["cantidad"]

# 2. Mostrar las primeras 4 filas
# de las columnas solicitadas
print(
    df[["id_venta", "precio", "cantidad", "venta_total"]].head(4)
)

   id_venta      precio  cantidad  venta_total
0         1  1140503.31         6   6843019.86
1         2  2786223.89         2   5572447.78
2         3   958850.40         3   2876551.20
3         4  1544815.40         5   7724077.00

Ejercicio 16: Detección de Valores Nulos

Contexto: Antes de proceder con limpiezas profundas, es indispensable cuantificar los datos faltantes en cada columna.

Instrucción: Utiliza la combinación de métodos .isna().sum() sobre el DataFrame para calcular el número total de valores nulos por columna e imprime el resultado.

In [20]:
# 1. Agrupar por categoría
# 2. Seleccionar venta_total
# 3. Sumar las ventas

ventas_categoria = (
    df.groupby("categoria")["venta_total"]
    .sum()
)

# 4. Mostrar el resultado
print(ventas_categoria)

categoria
Accesorios      5.482465e+08
ElectrÃ³nica    5.329718e+08
PerifÃ©ricos    5.633076e+08
Name: venta_total, dtype: float64

Ejercicio 17: Limpieza de Nulos - Imputación Numérica

Contexto: La columna "precio" contiene valores nulos que pueden alterar cálculos posteriores si no se corrigen.

Instrucción: Calcula el promedio de la columna "precio" usando .mean(). Luego, utiliza ese valor promedio para rellenar los nulos de la misma columna con el método .fillna(). Comprueba que el conteo de nulos en precio sea cero.

In [21]:
# Calcular el promedio de precio
promedio_precio = df["precio"].mean()

# Rellenar los valores nulos con el promedio
df["precio"] = df["precio"].fillna(promedio_precio)

# Comprobar que no queden valores nulos
print(df["precio"].isna().sum())

0

Ejercicio 19: Manipulación de Cadenas - Minúsculas y Espacios

Contexto: Las ciudades presentan variaciones tipográficas (como mayúsculas o espacios adicionales) que deben unificarse.

Instrucción: Utiliza el descriptor .str para transformar todos los textos de la columna "ciudad" a minúsculas y eliminar espacios sobrantes, guardando el resultado en una nueva columna llamada "ciudad_limpia". Muestra las primeras 4 filas.

In [22]:
# Limpiar la columna ciudad
df["ciudad_limpia"] = df["ciudad"].str.strip().str.lower()

# Mostrar las primeras 4 filas
print(df[["ciudad", "ciudad_limpia"]].head(4))

         ciudad ciudad_limpia
0  Barranquilla  barranquilla
1  Barranquilla  barranquilla
2          Cali          cali
3  Barranquilla  barranquilla


Ejercicio 20: Manipulación de Cadenas - Reemplazo de Textos

Contexto: Estandarizaremos los nombres de las categorías de productos para asegurar consistencia en los reportes ejecutivos.

Instrucción: Utiliza el método .str.replace() para modificar la columna "categoria", reemplazando cualquier ocurrencia de "Periféricos" por "Perifericos". Muestra una muestra de los datos modificados.

In [23]:
# Reemplazar el texto en la columna categoria
df["categoria"] = df["categoria"].str.replace(
    "Periféricos",
    "Perifericos"
)

# Mostrar una muestra de los datos modificados
print(df[["categoria"]].head())

      categoria
0    Accesorios
1    Accesorios
2    Accesorios
3  PerifÃ©ricos
4  PerifÃ©ricos

Ejercicio 22: Ordenamiento de Datos - Descendente

Contexto: La gerencia necesita identificar de inmediato las transacciones comerciales que generaron mayor ingreso total.

Instrucción: Asegúrate de tener calculada la columna "venta_total" y ordena el DataFrame de forma descendente (ascending=False) usando .sort_values(). Muestra las 3 transacciones principales.

In [24]:
df["venta_total"] = df["precio"] * df["cantidad"]

# Ordenar las ventas de mayor a menor
df_ordenado = df.sort_values(
    by="venta_total",
    ascending=False
)

# Mostrar las 3 ventas principales
print(df_ordenado.head(3))

     id_venta       fecha    producto     categoria      precio  cantidad  \
171       172  2024-05-06      Laptop  ElectrÃ³nica  3393019.34         9
162       163  2024-03-16  AudÃ­fonos  PerifÃ©ricos  3371830.55         9
59         60  2024-04-16       Mouse  ElectrÃ³nica  3364749.11         9

      ciudad metodo_pago cliente_satisfecho  venta_total ciudad_limpia
171  bogotÃ¡     Tarjeta                SÃ­  30537174.06       bogotã¡
162     Cali     Tarjeta                 No  30346474.95          cali
59       NaN         NaN                 si  30282741.99           NaN

Ejercicio 23: Agrupamiento Simple (groupby)

Contexto: Necesitamos conocer la cantidad total de unidades vendidas agrupadas por cada categoría de producto.

Instrucción: Utiliza .groupby("categoria") combinado con la función de agregación .sum() sobre la columna "cantidad" para obtener el total de unidades por categoría. Muestra el resultado.

In [25]:
unidades_categoria = (
    df.groupby("categoria")["cantidad"]
    .sum()
)

# Mostrar el resultado
print(unidades_categoria)

categoria
Accesorios      320
ElectrÃ³nica    318
PerifÃ©ricos    346
Name: cantidad, dtype: int64

Ejercicio 24: Agregaciones Múltiples con .agg()

Contexto: El departamento financiero requiere un reporte avanzado que detalle simultáneamente el ingreso total y el precio promedio por categoría.

Instrucción: Agrupa el DataFrame por "categoria" y utiliza el método .agg() para calcular la suma de "venta_total" y el promedio de "precio". Restablece el índice con .reset_index() y muestra la tabla resultante.

In [26]:
# Agrupar por categoría y hacer varias operaciones
resumen_categoria = (
    df.groupby("categoria")
    .agg({
        "venta_total": "sum",
        "precio": "mean"
    })
    .reset_index()
)

# Mostrar la tabla resultante
print(resumen_categoria)

      categoria   venta_total        precio
0    Accesorios  5.944888e+08  1.893713e+06
1  ElectrÃ³nica  5.720999e+08  1.745458e+06
2  PerifÃ©ricos  5.988785e+08  1.694110e+06

Ejercicio 25: Función Personalizada Aplicada al DataFrame (def + iteración/apply)

Contexto: Queremos clasificar cada transacción con una etiqueta de costo utilizando una función lógica personalizada.

Instrucción: Define una función llamada etiquetar_precio(precio) que retorne "Alto" si el precio es mayor a 1,500,000 y "Normal" en caso contrario. Utiliza un bucle for o aplica la lógica para mostrar la etiqueta de las primeras 5 filas de precios.

In [27]:
# Crear la función
def etiquetar_precio(precio):
    if precio > 1500000:
        return "Alto"
    else:
        return "Normal"


# Aplicar la función a los primeros 5 precios
for precio in df["precio"].head(5):
    etiqueta = etiquetar_precio(precio)
    print(precio, "→", etiqueta)

1140503.31 → Normal
2786223.89 → Alto
958850.4 → Normal
1544815.4 → Alto
1778548.2186315788 → Alto

Ejercicio 28: Uso de Bloque try-except para Conversión de Tipos

Contexto: Al transformar columnas de texto numérico a formato flotante o entero, pueden surgir errores por caracteres inesperados.

Instrucción: Escribe un bloque try-except que intente convertir una columna de texto arbitraria a entero mediante pd.to_numeric(..., errors='raise'). Si ocurre una excepción (ej. ValueError), captura el error e imprímelo informando de la anomalía de formato.

In [28]:
try:
    # Intentar convertir la columna precio a número entero
    df["precio"] = pd.to_numeric(
        df["precio"],
        errors="raise"
    ).astype(int)

    # Mensaje si la conversión funciona
    print("Conversión realizada correctamente")

except ValueError as error:
    # Capturar el error si hay un dato con formato incorrecto
    print("Error: hay un dato con formato incorrecto")
    print(error)

Conversión realizada correctamente

Ejercicio 29: Agrupamiento con Múltiples Dimensiones

Contexto: Necesitamos refinar nuestro análisis segmentando los datos tanto por ciudad como por categoría de producto de manera simultánea.

Instrucción: Agrupa el DataFrame utilizando una lista de columnas ["ciudad", "categoria"] y calcula el promedio de la columna "precio" mediante .mean(). Restablece el índice e imprime las primeras 5 filas.

In [29]:
# Agrupar por ciudad y categoría
promedio_precio = (
    df.groupby(["ciudad", "categoria"])["precio"]
    .mean()
    .reset_index()
)

# Mostrar las primeras 5 filas
print(promedio_precio.head(5))

         ciudad     categoria        precio
0        BOGOTA    Accesorios  1.703941e+06
1        BOGOTA  ElectrÃ³nica  1.702822e+06
2        BOGOTA  PerifÃ©ricos  1.432998e+06
3  Barranquilla    Accesorios  1.632228e+06
4  Barranquilla  ElectrÃ³nica  1.306867e+06

Ejercicio 30: Consolidación y Resumen Final con Funciones y Bucles

Contexto: Crearemos un bloque de script que combine lógica de funciones personalizadas y bucles para resumir estadísticas clave del dataset limpio.

Instrucción: Define una función que reciba un DataFrame y devuelva el ingreso total acumulado ("venta_total"). Utiliza un bucle for para iterar sobre las ciudades únicas del DataFrame, imprimiendo el ingreso total generado en cada ciudad específica calculado mediante un filtro dinámico.

In [30]:
# Calcular la venta total
df["venta_total"] = df["precio"] * df["cantidad"]


# Crear una función para calcular el ingreso total
def calcular_ingreso_total(datos):
    return datos["venta_total"].sum()


# Obtener las ciudades únicas
ciudades = df["ciudad"].unique()


# Recorrer cada ciudad
for ciudad in ciudades:

    # Filtrar los datos de la ciudad actual
    df_ciudad = df[df["ciudad"] == ciudad]

    # Calcular el ingreso total de esa ciudad
    ingreso = calcular_ingreso_total(df_ciudad)

    # Mostrar el resultado
    print("Ciudad:", ciudad, "| Ingreso total:", ingreso)

Ciudad: Barranquilla | Ingreso total: 287555851
Ciudad: Cali | Ingreso total: 271394914
Ciudad: bogotÃ¡ | Ingreso total: 340816152
Ciudad: BogotÃ¡ | Ingreso total: 263839028
Ciudad: MedellÃ­n | Ingreso total: 245306432
Ciudad: BOGOTA | Ingreso total: 245389357
Ciudad: nan | Ingreso total: 0

In [31]:
def clasificar_notas(notas):
    aprobados = 0
    no_aprobados = 0

    for nota in notas:
        if nota >= 3.0:
            aprobados += 1
        else:
            no_aprobados += 1

    return (aprobados, no_aprobados)

print(clasificar_notas([4.5, 2.8, 3.0, 1.9, 3.7]))

(3, 2)