1. Carga y Manipulación de Datos

Contexto: Iniciamos cargando el archivo de sucursales con valores nulos y generando columnas calculadas para enriquecer el análisis básico.

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv(
    'ejemplo.csv',
    sep=';',
    encoding='utf-8'
)

df

    ID    Ciudad Producto  Cantidad  Precio_Unitario Vendedor
0  101    Bogotá   Laptop       2.0           1200.0      Ana
1  102  Medellín    Mouse       NaN             25.0   Carlos
2  103      Cali  Teclado       5.0             45.0      Ana
3  104    Bogotá  Monitor       1.0            800.0      NaN
4  105  Medellín   Laptop       3.0           1200.0     Luis
5  106      Cali    Mouse      10.0             25.0   Carlos

In [4]:
# copia_df_or = df.copy()
# copia_df_or

In [6]:
df["Cantidad"] = df["Cantidad"].fillna(1)
df["Vendedor"] = df["Vendedor"].fillna("Jeff")

df

    ID    Ciudad Producto  Cantidad  Precio_Unitario Vendedor
0  101    Bogotá   Laptop       2.0           1200.0      Ana
1  102  Medellín    Mouse       1.0             25.0   Carlos
2  103      Cali  Teclado       5.0             45.0      Ana
3  104    Bogotá  Monitor       1.0            800.0     Jeff
4  105  Medellín   Laptop       3.0           1200.0     Luis
5  106      Cali    Mouse      10.0             25.0   Carlos

In [7]:
df["New_Col"] = "HHH"
df

    ID    Ciudad Producto  Cantidad  Precio_Unitario Vendedor New_Col
0  101    Bogotá   Laptop       2.0           1200.0      Ana     HHH
1  102  Medellín    Mouse       1.0             25.0   Carlos     HHH
2  103      Cali  Teclado       5.0             45.0      Ana     HHH
3  104    Bogotá  Monitor       1.0            800.0     Jeff     HHH
4  105  Medellín   Laptop       3.0           1200.0     Luis     HHH
5  106      Cali    Mouse      10.0             25.0   Carlos     HHH

In [8]:
df["New_Col"] = df["Cantidad"] * df["Precio_Unitario"]
df

    ID    Ciudad Producto  Cantidad  Precio_Unitario Vendedor  New_Col
0  101    Bogotá   Laptop       2.0           1200.0      Ana   2400.0
1  102  Medellín    Mouse       1.0             25.0   Carlos     25.0
2  103      Cali  Teclado       5.0             45.0      Ana    225.0
3  104    Bogotá  Monitor       1.0            800.0     Jeff    800.0
4  105  Medellín   Laptop       3.0           1200.0     Luis   3600.0
5  106      Cali    Mouse      10.0             25.0   Carlos    250.0

In [ ]:
# Imputamos la cantidad nula con un valor por defecto o promedio
df["Cantidad"] = df["Cantidad"].fillna(1)

# Creación de columna calculada
df["Venta_Total"] = df["Cantidad"] * df["Precio_Unitario"]

print(df[["ID_Pedido", "Producto", "Venta_Total"]].head(3))

2. Manipulación de Cadenas (.str)

Contexto: Estandarizamos los textos de las columnas categóricas (como convertir las ciudades a minúsculas o limpiar espacios) para asegurar que los filtros y agrupaciones no fallen por variaciones tipográficas.

In [11]:
# Estandarizar la columna 'Ciudad' a minúsculas y quitar espacios
df["Ciudad_Limpia"] = df["Ciudad"].str.lower().str.strip()
df

# Reemplazar valores de texto en nombres de productos si fuera necesario
#df["Producto"] = df["Producto"].str.replace("Mouse", "Ratón Óptico")

#print(df[["Ciudad", "Ciudad_Limpia", "Producto"]].head(3))

,ID,Ciudad,Producto,Cantidad,Precio_Unitario,Vendedor,New_Col,Venta_Total,Ciudad_Limpia
0,101,Bogotá,Laptop,2.0,1200.0,Ana,2400.0,2400.0,bogotá
1,102,Medellín,Mouse,1.0,25.0,Carlos,25.0,25.0,medellín
2,103,Cali,Teclado,5.0,45.0,Ana,225.0,225.0,cali
3,104,Bogotá,Monitor,1.0,800.0,Jeff,800.0,800.0,bogotá
4,105,Medellín,Laptop,3.0,1200.0,Luis,3600.0,3600.0,medellín
5,106,Cali,Mouse,10.0,25.0,Carlos,250.0,250.0,cali

In [13]:
# Reemplazar valores de texto en nombres de productos si fuera necesario
df["Producto"] = df["Producto"].str.replace("Mouse", "Ratón Óptico")
df

,ID,Ciudad,Producto,Cantidad,Precio_Unitario,Vendedor,New_Col,Venta_Total,Ciudad_Limpia
0,101,Bogotá,Laptop,2.0,1200.0,Ana,2400.0,2400.0,bogotá
1,102,Medellín,Ratón Óptico,1.0,25.0,Carlos,25.0,25.0,medellín
2,103,Cali,Teclado,5.0,45.0,Ana,225.0,225.0,cali
3,104,Bogotá,Monitor,1.0,800.0,Jeff,800.0,800.0,bogotá
4,105,Medellín,Laptop,3.0,1200.0,Luis,3600.0,3600.0,medellín
5,106,Cali,Ratón Óptico,10.0,25.0,Carlos,250.0,250.0,cali

In [14]:
print(df[["Ciudad", "Ciudad_Limpia", "Producto"]].head(3))

     Ciudad Ciudad_Limpia      Producto
0    Bogotá        bogotá        Laptop
1  Medellín      medellín  Ratón Óptico
2      Cali          cali       Teclado

3. Ordenamiento de Datos (sort_values)

Contexto: Ordenamos las transacciones comerciales de mayor a menor valor para destacar rápidamente los pedidos que generan más ingresos.

In [15]:
df_ordenado = df.sort_values(by='New_Col', ascending=True)
df_ordenado

,ID,Ciudad,Producto,Cantidad,Precio_Unitario,Vendedor,New_Col,Venta_Total,Ciudad_Limpia
1,102,Medellín,Ratón Óptico,1.0,25.0,Carlos,25.0,25.0,medellín
2,103,Cali,Teclado,5.0,45.0,Ana,225.0,225.0,cali
5,106,Cali,Ratón Óptico,10.0,25.0,Carlos,250.0,250.0,cali
3,104,Bogotá,Monitor,1.0,800.0,Jeff,800.0,800.0,bogotá
0,101,Bogotá,Laptop,2.0,1200.0,Ana,2400.0,2400.0,bogotá
4,105,Medellín,Laptop,3.0,1200.0,Luis,3600.0,3600.0,medellín

In [16]:
df_ordenado = df.sort_values(by="New_Col", ascending=False)

df_ordenado[["Vendedor", "New_Col"]].head(1)

  Vendedor  New_Col
4     Luis   3600.0

In [ ]:
# Ordenar por 'Venta_Total' de forma descendente
df_ordenado = df.sort_values(by="New_Col", ascending=False)

print("--- Transacciones ordenadas por mayor valor ---")
print(df_ordenado[["ID_Pedido", "Producto", "New_Col"]].head(3))

4. Agrupamiento y Agregaciones (groupby)

Contexto: Agrupamos las operaciones por dimensiones clave (por ejemplo, por Ciudad o por Vendedor) para resumir el rendimiento total del negocio.

En la parte inferior de la imagen empieza el siguiente código:

In [19]:
resumen_ciudad = df.groupby('Ciudad_Limpia')['New_Col'].sum()
resumen_ciudad

Ciudad_Limpia
bogotá      3200.0
cali         475.0
medellín    3625.0
Name: New_Col, dtype: float64

In [ ]:
# Agrupar por Ciudad sumando las ventas totales y promediando los precios
resumen_ciudad = df.groupby("Ciudad").agg(
    Ingreso_Total=("Venta_Total", "sum"),
    Precio_Promedio=("Precio_Unitario", "mean")
).reset_index()

In [20]:
resumen_ciudad = (df.groupby(['Ciudad_Limpia','Producto'])['New_Col']
                  .sum()
                  .sort_values(ascending=False)
                 )

resumen_ciudad
#resumen_ciudad

Ciudad_Limpia  Producto
medellín       Laptop          3600.0
bogotá         Laptop          2400.0
               Monitor          800.0
cali           Ratón Óptico     250.0
               Teclado          225.0
medellín       Ratón Óptico      25.0
Name: New_Col, dtype: float64